/// Flutter icons WeaponAim2
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeaponAim2
///      fonts:
///       - asset: fonts/WeaponAim2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WeaponAim2 {
  WeaponAim2._();

  static const _kFontFam = 'WeaponAim2';
  static const _kFontPkg = null;

  static const IconData iron_sigh_notarget = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
